# fly.toml app configuration file generated for convertx-spring-sound-7363 on 2025-07-22T01:54:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'convertx-spring-sound-7363'
primary_region = 'dfw'

[build]
  dockerfile = "Dockerfile"

[env]
  ACCOUNT_REGISTRATION = "true"
  HTTP_ALLOWED = "false"
  ALLOW_UNAUTHENTICATED = "false"
  AUTO_DELETE_EVERY_N_HOURS = "1"
  TZ = "America/Chicago"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = "convertx_data"
  destination = "/app/data"
  initial_size = "1gb"
