name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install --frozen-lockfile
    
    - name: Run type checking
      run: bun run lint:tsc
    
    - name: Run linting
      run: bun run lint
    
    - name: Build CSS
      run: bun run build
    
    - name: Build Docker image
      run: docker build -t convertx:test .
    
    - name: Test Docker image
      run: |
        docker run -d -p 3000:3000 --name convertx-test convertx:test
        sleep 5
        curl -f http://localhost:3000 || exit 1
        docker stop convertx-test
