name: Create Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun run build

      - name: Build Docker image
        run: docker build -t convertx:${{ github.ref_name }} .

      - name: Save Docker image
        run: docker save convertx:${{ github.ref_name }} | gzip > convertx-docker-${{ github.ref_name }}.tar.gz

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            convertx-docker-${{ github.ref_name }}.tar.gz
            compose.yaml
            README.md
          body: |
            ## ConvertX Release ${{ github.ref_name }}
            
            ### Docker Installation
            ```bash
            docker load < convertx-docker-${{ github.ref_name }}.tar.gz
            docker compose up -d
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
